/**
 * NJTC Portal — Asana Service Layer  v2.0  (GitHub-native)
 * ─────────────────────────────────────────────────────────────────
 * HOW THIS WORKS:
 *
 *   Instead of calling Asana from the browser (which requires a PAT
 *   and is blocked by CORS), this service reads a pre-built static
 *   file: /data/tasks.json
 *
 *   That file is written automatically by a GitHub Actions workflow
 *   (.github/workflows/sync-asana-tasks.yml) that runs on a cron
 *   schedule every 30 minutes. The workflow calls Asana using a PAT
 *   stored safely in GitHub Secrets — it never touches the browser.
 *
 *   This file only reads the result. No credentials here.
 *
 * REFRESH CADENCE:
 *   Tasks update every 30 minutes via GitHub Actions.
 *   The browser re-fetches tasks.json every 30 minutes to match.
 *   For a 90/60/30-day deadline system, 30-minute lag is fine.
 *
 * FUTURE MODULES:
 *   Other components can call AsanaService.fetchProjectTasks() or
 *   AsanaService.startPolling(callback) to get task data without
 *   caring how it was fetched. The interface is unchanged from v1.
 * ─────────────────────────────────────────────────────────────────
 */

// ── Configuration ─────────────────────────────────────────────────
const NJTC_ASANA_CONFIG = {
  // Path to the static tasks file generated by GitHub Actions.
  // This path is relative to the GitHub Pages root.
  tasksUrl: '/New-Jersey-Tutoring-Corps-Portal/data/tasks.json',

  // How often the browser re-reads tasks.json (milliseconds).
  // Set to match your GitHub Actions cron interval.
  pollIntervalMs: 30 * 60 * 1000, // 30 minutes
};

// ── AsanaService ───────────────────────────────────────────────────
const AsanaService = (() => {

  /**
   * Fetch tasks from the static tasks.json file.
   * Returns an array of task objects, or [] on any error.
   *
   * The cache-busting ?v= param ensures the browser always gets the
   * latest version even if GitHub Pages or a CDN has cached the file.
   */
  async function fetchProjectTasks() {
    const url = NJTC_ASANA_CONFIG.tasksUrl + '?v=' + Date.now();
    try {
      const response = await fetch(url, { cache: 'no-store' });
      if (!response.ok) {
        console.warn('[NJTC Asana] tasks.json returned', response.status,
          '— workflow may not have run yet.');
        return [];
      }
      const data = await response.json();
      // tasks.json shape: { "generated": "ISO timestamp", "tasks": [...] }
      if (!Array.isArray(data.tasks)) {
        console.warn('[NJTC Asana] tasks.json is missing the "tasks" array.');
        return [];
      }
      console.log(`[NJTC Asana] Loaded ${data.tasks.length} tasks (generated: ${data.generated})`);
      return data.tasks;
    } catch (err) {
      console.warn('[NJTC Asana] Could not load tasks.json:', err.message);
      return [];
    }
  }

  /**
   * Start polling. Calls onUpdate(tasks) immediately, then repeats
   * every pollIntervalMs. Returns a stop() function if you need to
   * cancel polling (e.g., on page unload).
   */
  function startPolling(onUpdate) {
    async function run() {
      const tasks = await fetchProjectTasks();
      onUpdate(tasks);
    }
    run(); // load immediately on page open
    const timer = setInterval(run, NJTC_ASANA_CONFIG.pollIntervalMs);
    return () => clearInterval(timer);
  }

  return { fetchProjectTasks, startPolling };
})();
